### ISSUE TITLE
3.1.67+

### ISSUE THREAD

**Issue by caperucitaferoz** [acestream/android-service-client-example#2]
The new versions of Ace Stream (for example 3.1.67) continue to work with this Intent?
```
// Intent for versions 3.1.43.0+
Intent intent = new Intent("org.acestream.action.start_content");
// start by content id
intent.setData(Uri.parse("acestream:?content_id=c894b23a65d64a0dae2076d2a01ec6bface83b01"));
// or start by transport file URL
intent.setData(Uri.parse("acestream:?url=" + Uri.encode("http://dl.acestream.org/sintel/sintel.torrent")));

// Uncomment this line to force starting playback in Ace Player (internal player of Ace Stream app)
//intent.putExtra("org.acestream.EXTRA_SELECTED_PLAYER", "{\"type\": 3}");
startActivity(intent);
```

**Comment by acestream** [comment]
It's a bug - we accidentally removed the intent "org.acestream.action.start_content" in the latest app versions.
Thanks for reporting.

The bug will be fixed in 3.1.67.3 in the coming days.
Until it's fixed you can use intent "android.intent.action.VIEW" instead of "org.acestream.action.start_content"

**Comment by caperucitaferoz** [comment]
Thanks to you for the quick response.
One more thing, this new version will also allow start by transport file URL? I think that in the last ones it did not work either

**Comment by acestream** [comment]
We have tested starting by transport file URL - it works fine, at least in the latest version (3.1.67.3).

It also should work in other versions. You can try this (using ADB):
```
adb shell am start -a android.intent.action.VIEW -d acestream:?url=http%3A%2F%2Fdl.acestream.org%2Fsintel%2Fsintel.torrent
```
